#!/usr/bin/env python3
import math
import stillsuit
import argparse
import os
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot
matplotlib.rcParams.update({
	"font.size": 12.0,
	"axes.titlesize": 12.0,
	"axes.labelsize": 12.0,
	"xtick.labelsize": 12.0,
	"ytick.labelsize": 12.0,
	"legend.fontsize": 10.0,
	"figure.dpi": 300,
	"savefig.dpi": 300,
	"path.simplify": True,
	"font.family": "serif"
})


def parse_command_line():
    parser = argparse.ArgumentParser(
        prog='plot-sim',
        description='This makes a missed found plot',
        epilog='I really hope you enjoy this program.')
    parser.add_argument('-s', '--config-schema', help="config schema yaml file")
    parser.add_argument('--input-db', help="the input database.")
    parser.add_argument('--output-name', help="the database to insert into. should not exist")
    parser.add_argument('-v', '--verbose', help="be verbose", action="store_true")
    args = parser.parse_args()

    return args

def compute_far(e):
    # Replace with real FAR calculation
    return math.exp(-e['event']['likelihood'])*10000

def main():
    args = parse_command_line()

    indb = stillsuit.StillSuit(config=args.config_schema, dbname=args.input_db)
    missed, found = indb.get_missed_found()
    pyplot.figure()
    pyplot.semilogy([m['geocent_end_time']/1e9 for m in missed], [(m['snr_H1']**2 + m['snr_L1']**2 + m['snr_V1']**2)**.5 for m in missed], 'k.', label="missed")
    pyplot.semilogy([f['simulation']['geocent_end_time']/1e9 for f in found], [(f['simulation']['snr_H1']**2 + f['simulation']['snr_L1']**2 + f['simulation']['snr_V1']**2)**.5 for f in found], 'g.', label="found")
    pyplot.xlabel('time')
    pyplot.ylabel('network snr')
    pyplot.grid()
    pyplot.legend()
    pyplot.savefig(args.output_name)


if __name__ == "__main__":
    main()
