{
 "title": "Main Analysis Dashboard greg",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "analysis", "query": "greg_test_icds" },
   { "name": "DashDatasource", "label": "Dashboard Datasource", "query": "influxdb" },
   {
    "name": "ginterval",
    "query": "{\"from\": $__from, \"to\": $__to}"
   },
   {
    "name": "far",
    "query": "{\"far\": \"$far_threshold\"}"
   },
   {
    "name": "pastro_name",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   },
   {
    "name": "trials_factor",
    "query": "{\"analysis\": \"$analysis\"}"
   },
   { "name": "far_threshold", "query": "7.72e-8" }
  ]
 },
 "panels": [
  {
   "title": "SNR History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "max H1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"H1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"L1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max V1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"V1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max H1 injection",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"inj_H1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "max L1 injection",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"inj_L1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "max V1 injection",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"inj_V1_snr_history\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Kafka OK",
     "query": "SELECT last(\"data\") FROM \"\".\"heartbeat\" WHERE \"data\" = 1 AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Kafka Not OK",
     "query": "SELECT last(\"data\") + 1 FROM \"\".\"heartbeat\" WHERE \"data\" = 0 AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Range History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_ifo]]",
     "query": "SELECT max(\"data\") FROM \"1s\".\"range_history\" WHERE $timeFilter GROUP BY time($__interval), \"ifo\" fill(null)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "# Helpful Links:\n\n# analysis name: ${analysis}\n\n**RRT Base Dashboard**: [here](https://ldas-jobs.gwave.ics.psu.edu/grafana/d/rrt-base/rapid-response-base-dashboard?orgId=1&refresh=5s)\n\n**GraceDB**: [latest GstLAL events](https://gracedb.ligo.org/latest/?query=gstlal&query_type=E&get_neighbors=&results_format=)\n\n**gwistat**: [online.igwn.org](https://online.igwn.org/)\n\n**All Sky Test Suite Dashboard**: [here](https://gstlal.ligo.caltech.edu/grafana/d/ccRx6r1Vk/test-suite-main?orgId=1&refresh=10s)\n\n"
   }
  },
  {
   "type": "ae3e-plotly-panel",
   "description": "Displays OK if a heartbeat has been received from the job in the last 5 minutes, DOWN otherwise.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "alias": "marginalize likelihoods",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "marginalize_likelihoods_online_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"marginalize_likelihoods_online_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "trigger counter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trigger_counter_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"trigger_counter_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "event plotter [[tag_heartbeat_tag]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_plotter_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"event_plotter_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY \"heartbeat_tag\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "event uploader",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_uploader_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"event_uploader_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "pastro uploader",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pastro_uploader_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"pastro_uploader_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "inj event uploader",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_uploader_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"inj_event_uploader_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "inj pastro uploader",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pastro_uploader_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"inj_pastro_uploader_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "inj event plotter [[tag_heartbeat_tag]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "heartbeat_tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_plotter_heartbeat",
     "query": "SELECT last(\"data\") FROM \"1s\".\"inj_event_plotter_heartbeat\" WHERE time >= now() - 5m and time <= now() GROUP BY \"heartbeat_tag\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Likelihood History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "injection likelihood",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inj_likelihood_history_across_svdbins",
     "query": "SELECT max(\"data\") FROM \"1s\".\"inj_likelihood_history_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "likelihood",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "likelihood_history_across_svdbins",
     "query": "SELECT max(\"data\") FROM \"1s\".\"likelihood_history_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "alias": "max injection",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"inj_latency_history_max_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "median injection",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"inj_latency_history_median_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "max",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"latency_history_max_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "median",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"latency_history_median_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "all_itacacac_latency",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"all_itacacac_latency\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "max",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"latency_history_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "median",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"latency_history_median\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "H1_whitening_latency",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"H1_whitening_latency\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "L1_whitening_latency",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"L1_whitening_latency\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "V1_whitening_latency",
     "query": "SELECT max(\"data\") FROM \"$ginterval\".\"V1_whitening_latency\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "FAR History",
   "type": "timeseries",
   "description": "False alarm rate history for all jobs. The analysis will not start assigning FARs until it has been calculating likelihoods for ~several hours.\nFAR thresholds:\n\nPurple: 1 per hr (gracedb upload threshold)\n\nBlue: 2 per day\n\nYellow: 1 per 5 months (Signif Alert Threshold)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "LOG10(min inj far)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inj_far_history_across_svdbins",
     "query": "SELECT LOG10(min(\"data\")) FROM \"1s\".\"inj_far_history_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "LOG10(min far)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inj_far_history_across_svdbins",
     "query": "SELECT LOG10(min(\"data\")) FROM \"1s\".\"far_history_across_svdbins\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IFAR ",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "query": "SELECT 1. / (86400*data) as ifar FROM \"10s\".\"far_history_across_svdbins\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max time since last metric",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "query": "SELECT first(ram) FROM (SELECT last(\"data\") as ram FROM \"1s\".\"ram_history\" WHERE $timeFilter);"
    },
    {
     "query": "SELECT first(ram) FROM (SELECT last(\"data\") as ram FROM \"1s\".\"inj_ram_history\" WHERE $timeFilter);"
    }
   ]
  },
  {
   "title": "RAM usage max across jobs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"data\") as \"RAM\" FROM \"$ginterval\".\"ram_history_across_svdbins\"  WHERE $timeFilter fill(null)"
    },
    {
     "query": "SELECT max(\"data\") as \"RAM\" FROM \"$ginterval\".\"inj_ram_history_across_svdbins\"  WHERE $timeFilter fill(null)"
    }
   ]
  },
  { "title": "Injection Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Decisive injected SNR vs. time (Bank cut)",
   "type": "timeseries",
   "description": "Orange: Missed (> 8.0)\nLight Blue: Missed (< 8.0)\nDark Blue: Found",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "missed (>= 8.0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "is_recovered" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "decisive_snr",
     "query": "SELECT \n    \"decisive_snr\" AS \"Dec. SNR\"\nFROM \"1s\".\"triggers\", \"missed_triggers\" WHERE (\"combined_far\" >= $far\nAND\n\"decisive_snr\" > 8.0\nAND\n((\"sim_mass1\" < 3.0 AND \"sim_mass2\" < 3.0 )\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" < 3.0 AND \"sim_mass1\" / \"sim_mass2\" <= 20)\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" >= 3.0 AND \"sim_spin2z\" < 0.99 AND \"sim_spin2z\" > -0.99 AND \"injchi_p\" < 0.001 AND \"sim_mass1\" / \"sim_mass2\" <= 20))) AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "is_recovered", "operator": "=", "value": "missed" }
     ]
    },
    {
     "alias": "missed (< 8.0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "is_recovered" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "decisive_snr",
     "query": "SELECT \n    \"decisive_snr\" AS \"Dec. SNR\"\nFROM \"1s\".\"triggers\", \"missed_triggers\" WHERE (\"combined_far\" >= $far\nAND\n\"decisive_snr\" < 8.0\nAND\n ((\"sim_mass1\" < 3.0 AND \"sim_mass2\" < 3.0 )\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" < 3.0 AND \"sim_mass1\" / \"sim_mass2\" <= 20)\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" >= 3.0 AND \"sim_spin2z\" < 0.99 AND \"sim_spin2z\" > -0.99 AND \"injchi_p\" < 0.001 AND \"sim_mass1\" / \"sim_mass2\" <= 20))) AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "is_recovered", "operator": "=", "value": "missed" }
     ]
    },
    {
     "alias": "found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "is_recovered" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "decisive_snr",
     "query": "SELECT \n    \"decisive_snr\" AS \"Dec. SNR\"\nFROM \"1s\".\"triggers\", \"missed_triggers\" WHERE (\"combined_far\" < $far\nAND\n((\"sim_mass1\" < 3.0 AND \"sim_mass2\" < 3.0 )\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" < 3.0 AND \"sim_mass1\" / \"sim_mass2\" <= 20)\nOR\n(\"sim_mass1\" + \"sim_mass2\" <= 400 AND \"sim_mass1\" >= 3.0 AND \"sim_spin1z\" < 0.99 AND \"sim_spin1z\" > -0.99 AND \"sim_mass2\" >= 3.0 AND \"sim_spin2z\" < 0.99 AND \"sim_spin2z\" > -0.99 AND \"injchi_p\" < 0.001 AND \"sim_mass1\" / \"sim_mass2\" <= 20))) AND $timeFilter",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "is_recovered", "operator": "=", "value": "missed" }
     ]
    },
    {
     "alias": "H1 ON",
     "query": "SELECT 90 * max(\"data\") FROM \"$ginterval\".\"H1_statevectorsegments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "L1 ON",
     "query": "SELECT 100*max(\"data\") FROM \"$ginterval\".\"L1_statevectorsegments\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Injection recovery efficiency (all above dec. SNR 8)",
   "type": "stat",
   "description": "FIXME: this calculation is finnicky. If any of the queries (found, missed, insig) return no data it will not work. This can happen if the time range is short or if the FAR threshold is too high or low.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "found",
     "query": "SELECT count(decisive_snr) AS found FROM \"1s\".\"triggers\" WHERE ($timeFilter AND decisive_snr > 8 AND \"combined_far\" < $far) fill(0);"
    },
    {
     "alias": "insig",
     "query": "SELECT count(decisive_snr) AS insig FROM \"1s\".\"triggers\" WHERE ($timeFilter AND decisive_snr > 8 AND \"combined_far\" >= $far) fill(0);"
    },
    {
     "alias": "missed",
     "query": "SELECT count(decisive_snr) AS missed FROM \"missed_triggers\" WHERE ($timeFilter AND decisive_snr > 8 AND \"combined_far\" >= $far) fill(0);"
    }
   ]
  },
  {
   "title": "p(astro) sankey diagram",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p_BNS",
     "query": "SELECT last(*) FROM \"1s\".\"source_class\" WHERE (\"name\"  =~ /^$pastro_name$/ AND \"combined_far\" < $far) AND $timeFilter GROUP BY time($__interval), \"source\" fill(null)",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "superevents" }
     ]
    }
   ]
  },
  {
   "title": "VT at 2/day (Mpc3 yr)",
   "type": "timeseries",
   "description": "Sensitive volume-time of the search in cubic Mpc-years. Calculated by counting the fraction of found injections (based on a FAR threshold of 2/day) multiplied the total injected VT. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_source]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vt",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      {
       "key": "far",
       "operator": "=",
       "value": "subthreshold oneperhour twoperday"
      }
     ]
    },
    {
     "alias": "expected [[tag_source]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exp_vt",
     "select": [
      [
       { "params": [ "data" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}